#!/bin/sh
pactl set-sink-volume 0 -5%;
dunstify  --icon=/usr/share/icons/gnome/256x256/status/stock_volume.png " $(pamixer --get-volume-human)" -h int:value:$(pamixer --get-volume-human) -r 1;
paplay /usr/share/sounds/Oxygen-Sys-App-Message.ogg;
